/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class AppTest {
    @Test 
    public void contextLoads() {
       // This test will pass if the application context loads successfully
    }
}
